import React, { useState } from 'react'
import { Share2, Download, Mail, MessageSquare, Copy, Lock } from 'lucide-react'
import Card from './Card'
import Button from './Button'

const InteractionSummary = ({ language, isSubscribed, onUpgrade }) => {
  const [summaryData, setSummaryData] = useState({
    date: new Date().toISOString().split('T')[0],
    time: new Date().toLocaleTimeString(),
    location: '',
    officerBadge: '',
    interaction: '',
    notes: ''
  })
  const [generatedSummary, setGeneratedSummary] = useState('')
  const [showSummary, setShowSummary] = useState(false)

  const handleInputChange = (field, value) => {
    setSummaryData(prev => ({
      ...prev,
      [field]: value
    }))
  }

  const generateSummary = () => {
    if (!isSubscribed) {
      onUpgrade()
      return
    }

    const summary = language === 'en' 
      ? `INTERACTION SUMMARY

Date: ${summaryData.date}
Time: ${summaryData.time}
Location: ${summaryData.location || 'Not specified'}
Officer Badge: ${summaryData.officerBadge || 'Not provided'}

INTERACTION TYPE: ${summaryData.interaction || 'Not specified'}

DETAILS:
${summaryData.notes || 'No additional notes provided'}

YOUR RIGHTS:
• You have the right to remain silent
• You have the right to refuse consent to searches
• You have the right to ask if you are free to leave
• You have the right to an attorney

This summary was generated by Pocket Parley for documentation purposes.`
      : `RESUMEN DE INTERACCIÓN

Fecha: ${summaryData.date}
Hora: ${summaryData.time}
Ubicación: ${summaryData.location || 'No especificado'}
Placa del Oficial: ${summaryData.officerBadge || 'No proporcionado'}

TIPO DE INTERACCIÓN: ${summaryData.interaction || 'No especificado'}

DETALLES:
${summaryData.notes || 'No se proporcionaron notas adicionales'}

SUS DERECHOS:
• Tiene derecho a permanecer en silencio
• Tiene derecho a rechazar el consentimiento para registros
• Tiene derecho a preguntar si es libre de irse
• Tiene derecho a un abogado

Este resumen fue generado por Pocket Parley con fines de documentación.`

    setGeneratedSummary(summary)
    setShowSummary(true)
  }

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedSummary)
    alert(language === 'en' ? 'Summary copied to clipboard!' : '¡Resumen copiado al portapapeles!')
  }

  const shareViaEmail = () => {
    const subject = language === 'en' ? 'Police Interaction Summary' : 'Resumen de Interacción Policial'
    const body = encodeURIComponent(generatedSummary)
    window.open(`mailto:?subject=${subject}&body=${body}`)
  }

  const shareViaText = () => {
    if (navigator.share) {
      navigator.share({
        title: language === 'en' ? 'Interaction Summary' : 'Resumen de Interacción',
        text: generatedSummary
      })
    } else {
      copyToClipboard()
    }
  }

  return (
    <div className="space-y-6">
      <Card>
        <div className="flex items-center gap-3 mb-6">
          <Share2 className="h-6 w-6 text-primary" />
          <h2 className="text-2xl font-semibold text-text-primary">
            {language === 'en' ? 'Interaction Summary' : 'Resumen de Interacción'}
          </h2>
        </div>

        <div className="grid md:grid-cols-2 gap-4 mb-6">
          <div>
            <label className="block text-sm font-medium text-text-primary mb-1">
              {language === 'en' ? 'Date:' : 'Fecha:'}
            </label>
            <input
              type="date"
              value={summaryData.date}
              onChange={(e) => handleInputChange('date', e.target.value)}
              className="w-full p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary focus:border-transparent"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-text-primary mb-1">
              {language === 'en' ? 'Time:' : 'Hora:'}
            </label>
            <input
              type="time"
              value={summaryData.time}
              onChange={(e) => handleInputChange('time', e.target.value)}
              className="w-full p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary focus:border-transparent"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-text-primary mb-1">
              {language === 'en' ? 'Location:' : 'Ubicación:'}
            </label>
            <input
              type="text"
              value={summaryData.location}
              onChange={(e) => handleInputChange('location', e.target.value)}
              placeholder={language === 'en' ? 'Street address or landmark' : 'Dirección o punto de referencia'}
              className="w-full p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary focus:border-transparent"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-text-primary mb-1">
              {language === 'en' ? 'Officer Badge #:' : 'Placa del Oficial #:'}
            </label>
            <input
              type="text"
              value={summaryData.officerBadge}
              onChange={(e) => handleInputChange('officerBadge', e.target.value)}
              placeholder={language === 'en' ? 'Badge number (if visible)' : 'Número de placa (si es visible)'}
              className="w-full p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary focus:border-transparent"
            />
          </div>
        </div>

        <div className="mb-4">
          <label className="block text-sm font-medium text-text-primary mb-1">
            {language === 'en' ? 'Interaction Type:' : 'Tipo de Interacción:'}
          </label>
          <select
            value={summaryData.interaction}
            onChange={(e) => handleInputChange('interaction', e.target.value)}
            className="w-full p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary focus:border-transparent"
          >
            <option value="">
              {language === 'en' ? 'Select interaction type...' : 'Seleccionar tipo de interacción...'}
            </option>
            <option value="traffic-stop">
              {language === 'en' ? 'Traffic Stop' : 'Parada de Tráfico'}
            </option>
            <option value="questioning">
              {language === 'en' ? 'Questioning/Detention' : 'Interrogatorio/Detención'}
            </option>
            <option value="search">
              {language === 'en' ? 'Search Request' : 'Solicitud de Registro'}
            </option>
            <option value="arrest">
              {language === 'en' ? 'Arrest' : 'Arresto'}
            </option>
            <option value="other">
              {language === 'en' ? 'Other' : 'Otro'}
            </option>
          </select>
        </div>

        <div className="mb-6">
          <label className="block text-sm font-medium text-text-primary mb-1">
            {language === 'en' ? 'Additional Notes:' : 'Notas Adicionales:'}
          </label>
          <textarea
            value={summaryData.notes}
            onChange={(e) => handleInputChange('notes', e.target.value)}
            placeholder={language === 'en' 
              ? 'Describe what happened, what was said, and any other relevant details...'
              : 'Describa lo que pasó, lo que se dijo y cualquier otro detalle relevante...'
            }
            rows={4}
            className="w-full p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary focus:border-transparent"
          />
        </div>

        <Button
          variant="primary"
          onClick={generateSummary}
          disabled={!isSubscribed}
          className="w-full flex items-center gap-2"
        >
          <Share2 className="h-4 w-4" />
          {language === 'en' ? 'Generate Summary' : 'Generar Resumen'}
        </Button>

        {!isSubscribed && (
          <div className="mt-4 p-4 bg-gray-50 rounded-md border">
            <div className="flex items-center gap-2 mb-2">
              <Lock className="h-4 w-4 text-text-secondary" />
              <span className="text-sm font-medium text-text-secondary">
                {language === 'en' ? 'Premium Feature' : 'Función Premium'}
              </span>
            </div>
            <p className="text-sm text-text-secondary mb-3">
              {language === 'en' 
                ? 'Generate professional interaction summaries with legal information and share them securely.'
                : 'Genere resúmenes profesionales de interacciones con información legal y compártalos de forma segura.'
              }
            </p>
            <Button variant="secondary" size="sm" onClick={onUpgrade}>
              {language === 'en' ? 'Upgrade to Premium' : 'Actualizar a Premium'}
            </Button>
          </div>
        )}
      </Card>

      {showSummary && generatedSummary && (
        <Card variant="highlighted">
          <h3 className="text-lg font-semibold text-text-primary mb-4">
            {language === 'en' ? 'Generated Summary' : 'Resumen Generado'}
          </h3>

          <div className="bg-gray-50 p-4 rounded-md mb-4 border">
            <pre className="whitespace-pre-wrap text-sm text-text-primary font-mono">
              {generatedSummary}
            </pre>
          </div>

          <div className="flex flex-wrap gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={copyToClipboard}
              className="flex items-center gap-2"
            >
              <Copy className="h-4 w-4" />
              {language === 'en' ? 'Copy' : 'Copiar'}
            </Button>

            <Button
              variant="outline"
              size="sm"
              onClick={shareViaEmail}
              className="flex items-center gap-2"
            >
              <Mail className="h-4 w-4" />
              {language === 'en' ? 'Email' : 'Correo'}
            </Button>

            <Button
              variant="outline"
              size="sm"
              onClick={shareViaText}
              className="flex items-center gap-2"
            >
              <MessageSquare className="h-4 w-4" />
              {language === 'en' ? 'Share' : 'Compartir'}
            </Button>

            <Button
              variant="outline"
              size="sm"
              onClick={() => {
                const blob = new Blob([generatedSummary], { type: 'text/plain' })
                const url = URL.createObjectURL(blob)
                const a = document.createElement('a')
                a.href = url
                a.download = `interaction-summary-${summaryData.date}.txt`
                a.click()
                URL.revokeObjectURL(url)
              }}
              className="flex items-center gap-2"
            >
              <Download className="h-4 w-4" />
              {language === 'en' ? 'Download' : 'Descargar'}
            </Button>
          </div>
        </Card>
      )}
    </div>
  )
}

export default InteractionSummary